[package]
name = "bucketsort"
version = "0.1.0"
authors = ["Nico <Nico.Westerbeck@mailbox.tu-dresden.de>"]

[dependencies]
getopts = "0.2"
time = "0.1"

clippy = {version = "*", optional = true}

[features]
lints = ["clippy"]

